[options]
admin_passwd = 1234
db_host = False
db_port = 5432
db_user = odoo18
db_password = odoo18
xmlrpc_port = 8069
http_interface = 127.0.0.1
addons_path = C:\Users\INFO STORE\OneDrive\Desktop\odoo-18.0+e.20250713\odoo\addons,C:\Users\INFO STORE\OneDrive\Desktop\odoo-18.0+e.20250713\custom_addons
